# Generated by Django 5.0.6 on 2026-01-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sugar_g_100g',
            field=models.FloatField(default=0.0),
        ),
    ]
