# Generated by Django 5.0.6 on 2026-01-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_sugar_g_100g'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast (eggs, oats, yogurt)'), ('PROTEIN', 'Protein (meat, fish, tofu)'), ('CARBS', 'Carbs (rice, pasta, potato)'), ('VITAMINS', 'Vitamins (vegetables, fruits, salad)'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='L', max_length=1),
        ),
    ]
